- components/apply/AppForm.tsx
- components/common/SelectInput.tsx
- components/common/TextAreaInput.tsx
- components/common/TextInput.tsx
- package.json
- tailwind.config.js
- yarn.lock
- Added `SelectInput`, `TextAreaInput`, and `TextInput` components for form fields
- Updated `AppForm` to include test these components - will remove before merging
1. Navigate to Netlify deployment preview and play with the components
- Functionality, consistent styling
> Create SelectInput, TextAreaInput, and TextInput form components

- components/apply/AppForm.tsx
- components/apply/ShortAnswers.tsx
- Created short answers section in `ShortAnswers.tsx` component
- Used `TextAreaInput` component for the text boxes
1. Go to `http://localhost:3000/apply`
2. Check that the section looks good
-  Questions and styling are correct
> Create short answers questions section

- components/apply/AppForm.tsx
- components/apply/BasicInfo.tsx
- components/apply/ShortAnswers.tsx
- Adds frontend for Basic Info application section
- All inputs except `resume` and `termType` use `/common` components
1. go to [https://deploy-preview-86--uwblueprint.netlify.app/apply](https://deploy-preview-86--uwblueprint.netlify.app/apply)
2. verify that Basic Information looks good
- Does the styling look correct?
> Basic Information Section

- components/apply/AppForm.tsx
- components/apply/InfoText.tsx
- pages/apply.tsx
- Added and styled header text for application. 
1. Ensure links are working and open new tabs rather than redirect current tab.
2. Ensure text styling matches previous application.
- Inline styling
> Add application header text section

- components/apply/AppForm.tsx
> Add readOnly prop to AppForm

- components/apply/AppForm.tsx
- components/apply/InfoText.tsx
- `InfoText` displays timestamp if read only
1. Ensure `InfoText` looks like:
> Add read only to infotext

- components/admin/ApplicationsTable.tsx
- pages/admin/index.tsx
- Used Firebase `get()` function to retrieve all applications
- Filtered applications by `term` and set to `applications` state
1. Go to `http://localhost:3000/admin`
2. Console log `applications` state
3. Check all applications are from `APPLICATION_TERM`
- Code correctness
> Firebase API call to retrieve all applications

- components/admin/ApplicationsTable.tsx
- pages/admin/index.tsx
- Makes default filter option to show all applications
- Filters applicants based on if the the filtered option is one of their first or second choice roles
1. Go to `http://localhost:3000/admin`
2. Check that default behaviour ("Select an option" in dropdown menu) is that all applications are shown
3. Try out the different filters and check that the applicants have the role from the dropdown is one of their role choices
- Check that the filters work correctly!
> Adds filtering applications by role to admin page

- constants/members.json
- Changed `term` value in `members.json` to update to new term.
> [Fix] Changed Term for Photo Images

- constants/members.json
- Updated members.json for the Internal Tools and Feeding Canadian Kids teams according to the W23 members spreadsheet.
1. Check members.json to make sure all names and associated pictures match with inputted members.
-
> Updating Student Images: FCK and Internal Tools

- constants/members.json
- Updated student images and roles for Caring Partners Global team
1.
-
> Updating Student Images: Caring Partners Global

- .eslintrc
- constants/members.json
Updated team to reflect Winter 23 information. Added eslint config change to fix said issue.
> Updated to winter 23 information for Jump Math

- constants/members.json
[Updating Student Images: Canadian Children Book Centre [CCBC]](https://www.notion.so/uwblueprintexecs/58fdb7043f98414aa6f88c7ec827d5ca?v=9df8cc8e794b4d9ea4152c1253b876d6&p=81ab34702c064919bce480e38a46cd37&pm=s)
-
1. Check the members.json and verify that all the members have the correct name, role, term, team and img
-
> Updating Student Images: CCBC

- components/members/utils.ts
- constants/members.json
[Updating Student Images: Add Designers and Other Roles to the E-Team](https://www.notion.so/uwblueprintexecs/Updating-Student-Images-Add-Designers-and-Other-Roles-to-the-E-Team-f54e80826a7249cc83148fd7e761a6fc)
- Updated terms to 1231, team to E-team, and changed to appropriate roles
- Added specific roles in **`utils.ts`**
- Make sure the term, team, and role are correct
> added designers to e-team

- constants/members.json
Ticket link: https://www.notion.so/uwblueprintexecs/58fdb7043f98414aa6f88c7ec827d5ca?v=9df8cc8e794b4d9ea4152c1253b876d6&p=7e41474e77ea47398fe36c0219fd118f&pm=s
- Updated members.json for all CASA team members.
1.
-
> Updating Student Images: CASA

- constants/members.json
- changed Caring Partners Global to Supportive Housing of Waterloo, both in name and id
- deleted extraneous entry
1.
-
> Photos Cleanup: Change Team Name & One Picture

- components/members/utils.ts
- constants/members.json
- Changed images for Deen and Vyomesh
- Change titles of some alumni to Project Lead
1. Look at website
-
> [Fix] Image & Title Changes

- components/admin/ApplicationsTable.tsx
- components/apply/AppForm.tsx
- components/apply/RoleSpecificQuestions.tsx
- components/join/OurProcess.tsx
- constants/applications.ts
- constants/role-specific-questions.json
- Add new PL application question
- Add option for hiding duplicate questions
- Update application timeline for the current term
I broke the changes down by commit, so I'd highly recommend reviewing that way!
1. Pull these changes locally (deploy preview won't work since the application period is not yet open).
2. Manually update the application START date to a date in the past (e.g., `"Feb 1 2023 00:00:00 EDT"`).
3. View the changes locally.
- Do you think this is the cleanest way to implement question aggregation?
> Update engineering application questions for S23 hiring round

- constants/applications.ts
- Update dates
1. View preview and check dates
-
> [hotfix] Update application dates to reflect latest VPT info

- components/apply/AppForm.tsx
- components/join/FAQ.tsx
- constants/role-specific-questions.json
- Hide content strategist role
- Fix random build error that was showing up locally
1. 
-
> Hide Content Strategist role

- constants/role-specific-questions.json
- Hide UXR role
1. Go to apply page and verify UXR doesn't appear in role dropdown anymore
-
> Hide UXR role

- components/apply/RoleSpecificQuestions.tsx
Firebase refuses to store empty arrays, so the `questions` property would go missing for applications to roles with no role-specific questions. To fix this, we'll simply filter out cases with missing questions.
1. Create an application to the VP Product role locally.
2. View the application on the admin page locally.
-
> [hotfix] Handle empty question arrays properly

- constants/role-specific-questions.json
This reverts commit 90724f2edbb97035a5aa1518fce9b975c5a0d827.
- Show UXR role again, as per VPT request
1. Go to apply page and verify UXR appears in role dropdown again
-
> Revert "Hide UXR role (#119)"

- components/apply/BasicInfo.tsx
- Modify term regex to allow "Graduate student"
1. Test field
-
> Let grad students apply

- constants/applications.ts
> Extend application deadline for S23

- components/apply/AppForm.tsx
- components/join/OurProcess.tsx
- constants/applications.ts
- package.json
- pages/admin/index.tsx
- utils/dayjs.ts
- yarn.lock
- Fix DST issues so we see the correct apps (yay more apps!)
- Add grace period to application deadline
1. View the admin page and verify that random (spotchecked) apps look like they have correct app dates.
-
> Fix application deadline issues

- constants/role-specific-questions.json
- https://uwblueprint.slack.com/archives/C04SSCCPMB3/p1678139166682419
1. Verify existing design apps still look good.
-
> Update design application questions for next term based on Slack discussion

- components/admin/ApplicationsTable.tsx
- components/admin/ApplicationsTableColumn.tsx
- package.json
- pages/admin/index.tsx
- yarn.lock
This PR adds the MUI datatable package and sets up the skeleton component for the table using new table headers.
See here for MUI data table functions available: https://github.com/gregnb/mui-datatables#options
See here for example of a blueprint project using MUI data table: https://github.com/uwblueprint/ccbc/blob/development/frontend/src/components/pages/AdminDashboard/AdminReviews.tsx
TO DO:
- Use `students` to generate the actual data in the table
- General table styling: find elements in the data table by inspecting using dev tools and override styles by replacing them in `override` in `createTheme`
- To render a component in a column (e.g. dropdown component) use `customBodyRender` in `options` in `columns`
- Added MUI datatable
1.
-
> Set up MUI data table

- styles/Theme.ts
> fix: added new colors to theme

- components/members/utils.ts
- constants/members.json
- graphql/queries.ts
- pages/admin/log-in/index.tsx
- pages/admin/login-success/index.tsx
- pages/admin/login/index.tsx
[Authorization Login Panel on /admin page of website-bp](https://www.notion.so/uwblueprintexecs/Authorization-Login-Panel-on-admin-page-of-website-bp-ac2e20dbf9e640edb54793098cae2afd)
- Added login page at **`pages/admin/login`** and login success page at **`pages/admin/login-success`** 
- Able to send GraphQL request using the fetch API
1. Run the frontend and backend repos
2. Ensure that the database is setup correctly
3. Login in with username: `recruitmenttools@uwblueprint.org` and password: `myblueprint!`
4. Try any other username password combination
-
> Authorization Login Panel on /admin page of website-bp

- constants/members.json
-Added new exec team members with their pictures and updated their term numbers to current term (1235)
1. Check that all of the exec team members in https://docs.google.com/spreadsheets/d/1qRm4LCmVLX2h1aSF-mKPMQME182NMkIfQ1Qm9n3cgbQ/edit#gid=0 show up with their pictures. 
-
> Add executive team pictures for current term 1235

- components/icons/error.icon.tsx
- pages/admin/login/index.tsx
- Added error states
1. Incorrect credentials
2. Try logging in without username or password
-
> Login screen state errors

- constants/members.json
- Updates the members list for Haven, FCK
> Update members list: Haven and FCK

- constants/members.json
Finalizes the `members.json` student list. 
* Fixes a few allocations
* Standardizes terminology
> Finalize members.json

- constants/members.json
- Changed one link to fix a picture
> Update profile picture

- constants/members.json
> Change Lauren to SHOW Team

- components/admin/ApplicationsTable.tsx
- components/common/Login.tsx
- components/context/ProtectedRoute.tsx
- graphql/queries.ts
- utils/makegqlrequest.ts
- utils/secrets.ts
- Added the environment variable `BE_DEPLOYMENT_DOMAIN` and used it to create a simpler fetch helper that just takes the query and the variable for the query.
> [Fix]: Added BE Fetch Utility & Env Variable for BE Deployment Domain

- components/common/Login.tsx
- components/context/AuthUserContext.tsx
- components/context/ProtectedRoute.tsx
- pages/admin/index.tsx
- Seems that signInWithRedirect wasn't triggering onAuthStateChange. Thus we now use signInWithPopup
1.
-
> fix redirect to admin after login

- constants/role-specific-questions.json
Adds the UX content writer role
> Add UX content writer

- components/admin/ApplicationsTable.tsx
- components/icons/copy.icon.tsx
- styles/Theme.ts
applies initial style changes to the application table
> initial application table style

- components/admin/ApplicationsTable.tsx
… and faster
- Added some new backend API endpoints to clean up data transfer for the application table. Makes the flow cleaner, less prone to server errors, and faster.
1. load up localhost and navigate to the application table page.
-
> Combined all GraphQL requests for Application Table into one

- components/review/shared/reviewSplitPanelPage.tsx
- components/review/shared/reviewStepper.tsx
- components/review/stages/reviewAnswers.tsx
- components/review/stages/reviewInfoStage.tsx
- components/review/stages/reviewRubric.tsx
Makes the review flow work more cleanly on smaller screens.
> Fix reviews for smaller screens

- constants/members.json
- Updated term number
- Added new team name+id
- Add new bp members
1. 
- Check if new team name+id are fine
> Students 36 52

- constants/members.json
- Updated member row 53 - 69 & Team Children's Aid Society
1.
-
> Lucy/updated 53-59 + CAS

- constants/members.json
- Changed term to 1236 and updated team/role/picture link for existing members
- Created new object for new members
1.
-
> annie: updated team members 2-18 and executives team

- constants/members.json
-Changed term to 1236 and updated team/role/picture link for existing members
-Created new object for new members
1.
-
> Add fall 2023 photos 70-84

- constants/members.json
Deletes old branch and pastes contents into new branch which branches off of main. 
old branch: updating_pics_anusheh
new branch: updating_pics_anusheh2
Updated teams: 
SHOW
Marillac
Internal Tools
-
1.
-
> fixing initial commit for image upload

- constants/members.json
- constants/role-specific-questions.json
- removes UX Content Writer and User Experience Researcher from the open positions - we aren't hiring for those roles this term 
- updates Chris Pan img 
1. check if the positions do not come up in the drop down menu of the application
2. Photo for Chris Pan is right 
-
> removes non hiring positions and updates img

- components/join/Hero.tsx
> fixes apply now button responsive colour

- components/admin/ApplicationsTable.tsx
Redirect user to application page when they click on an application from the application dashboard table 
- Use router.push to redirect to application based on application id
- Integrating protectedApplication.tsx to ensure only reviewer 1 and 2 can view the application
1.
-
> [INTF23] - Redirect Application

- .github/pull_request_template.md
> Updates pull_request_template to include ticket name

- components/admin/ApplicationsTable.tsx
- components/admin/DropdownMenu.tsx
- components/admin/RoleHeader.tsx
- components/admin/Table.tsx
- styles/globals.css
- tailwind.config.js
- utils/muidatatable.tsx
[Update Applicant Dashboard UI](https://www.notion.so/uwblueprintexecs/Update-Applicant-Dashboard-UI-e88cd12bbf784e3fa5e049d46a5c7f5b?pvs=4)
* Moved DropdownMenu component in Table.tsx and changed its styling according to the design
* Added w-max to Status and SecondChoiceStatus components
* Added utils path to tailwind-config.ts
* Added missing status/second choice status to utils
1.
*
> [INTF23] Update Dashboard UI

- components/review/stages/reviewInfoStage.tsx
- graphql/queries.ts
- pages/review/index.tsx
- pages/review/protectedApplication.tsx
- types.ts
[Ticket Name](https://www.notion.so/uwblueprintexecs/Review-Page-Info-Page-ab7ccd7e80a94495b482632819c23bda)
* Set up query to fetch application data by id
* Extract data to the info page and set up display
> 
> 
1. check http://localhost:3000/review?reviewId=1 (make sure your own username has access)
* How data is extracted and integrated on the info page
> [INTF23] Updates Info Section in Review Page - Cherry-picked Version 

- components/review/stages/reviewInfoStage.tsx
- graphql/queries.ts
- pages/review/index.tsx
No ticket
- adds missing variables
- fixes `graphql/queries.ts` query error
1. Check out the info section in the review page and ensure all information is being correctly displayed
*
> [INTF23] Fixes info section bugs

- APIClients/AuthAPIClient.ts
- components/admin/ApplicationsTable.tsx
- components/admin/DashboardTableTitle.tsx
- components/admin/Table.tsx
- graphql/queries.ts
- pages/review/index.tsx
- types.ts
[Ticket Name](https://www.notion.so/uwblueprintexecs/Task-Board-db95cd7b93f245f78ee85e3a8a6a316d)
* linting files
1. Double check with `yarn lint`
*
> [INTF23] Linting

- components/review/stages/reviewDriveToLearnStage.tsx
- pages/review/index.tsx
[Review Page - D2L Page](https://www.notion.so/uwblueprintexecs/Review-Page-D2L-Page-02c888afcab04ca8b504205d77d9e5d0)
* Fetch & extract applicant info based on Id. 
* Display info on D2L page.
1. check http://localhost:3000/review?reviewId=1 (make sure your own username has access)
* Review the data displayed on the D2L page
* Ensure that both the rubrics & the question/response are displayed properly
> [INTF23] Updates D2L Section in Review Page

- APIClients/AuthAPIClient.ts
- components/admin/ReviewTable.tsx
- components/admin/Table.tsx
- components/review/shared/reviewRatingPage.tsx
- components/review/stages/reviewAnswers.tsx
- components/review/stages/reviewDriveToLearnStage.tsx
- components/review/stages/reviewPassionForSocialGoodStage.tsx
- components/review/stages/reviewRubric.tsx
- components/review/stages/reviewTeamPlayerStage.tsx
- pages/review/index.tsx
[Review Page - (PFSG/TP) page ](https://www.notion.so/uwblueprintexecs/58fdb7043f98414aa6f88c7ec827d5ca?v=9df8cc8e794b4d9ea4152c1253b876d6&p=a57bbb10d71a435483e08efe8dd7870d&pm=s)
* refactored TP and PFSG page to align with other pages
* modified scoring context position on TP and PFSG review pages
1. Score panel should be on the right side of the respective review pages under answers. 
* N/A
> [INTF23] PFSG and TP review page

- components/admin/ExpandableRowTable.tsx
- components/admin/ReviewTable.tsx
- components/admin/Table.tsx
- tailwind.config.js
- utils/muidatatable.tsx
[Review Dashboard Expandable Row](https://www.notion.so/uwblueprintexecs/Review-Dashboard-Expandable-Row-px-43b5dc9deace4b87a0399409968a26b7?pvs=4)
* Used MUI datatable expandable row options
* Added inner table called ExpandableRowTable component and rendered that inside each expandable row
1.
*
> [INTF23] Review Dashboard Expandable Row

- constants/members.json
[Updating ETeam](https://www.notion.so/uwblueprintexecs/Updating-ETeam-49f131b151524ad995ff7698ec675f52)
* Updated executive team for W24
1. Load the frontend
* Changes to the `members.json` file
> update eteam for w24

- constants/members.json
[Updating FCK](https://www.notion.so/uwblueprintexecs/Updating-FCK-9ab94e0123e34ed2b772d06922374342?pvs=4)
Updated members.json with new information from the W24 Team Update google sheet (FCK team): https://docs.google.com/spreadsheets/d/1Lrn_g7Z92x4EPZ2OUkn3Vo1QSb5SbfqYQxAagr6zeVg/edit?pli=1#gid=0
Ensure the FCK team is consistent with the google sheets
Make sure constants\members.json is consistent with the above google sheet
> Updates members.json with new FCK members

- constants/members.json
[Updating CAS](https://www.notion.so/uwblueprintexecs/Updating-CAS-4cf791d98ecb403b90f64d6dbbe03862?pvs=4)
Updated members.json with new information from the W24 Team Update google sheet: https://docs.google.com/spreadsheets/d/1Lrn_g7Z92x4EPZ2OUkn3Vo1QSb5SbfqYQxAagr6zeVg/edit?pli=1#gid=0
Ensure the CAS team is consistent with the google sheets
Make sure constants\members.json is consistent with the above google sheet
> updates members.json file with new members for CAS

- constants/members.json
[Ticket Name](https://www.notion.so/uwblueprintexecs/Updating-Marilliac-Place-38f808f26ebd48eebb1040a680af76de)
* Adding members for marillac place
>  add team members for marillac place 

- constants/members.json
[Updating CWC](https://www.notion.so/uwblueprintexecs/Updating-CWC-6fcfbc3bf35448d6a1b040238fd72dc5)
* Updating CWC members for Blueprint website
1. Run yarn dev
2. Navigate to the students tab
3. Verify that all the members of the CWC team are there
*
> Updating CWC members

- constants/members.json
[Updating Internal Tools](https://www.notion.so/uwblueprintexecs/Updating-Internal-Tools-16aa8b2bcbeb492696d6e2f982c8933e?pvs=4)
* Added and changed members for the internal tools team on the bp website under students
1. yarn dev
2. students tab
3. check if all the members of the team are there
*
> internal tools member changes

- constants/members.json
[Updating Don Efficace](https://www.notion.so/uwblueprintexecs/Updating-Don-Efficace-cab5b3852ae3414696c20a77cec35b60?pvs=4)
* Updated members.json with new information from the W24 Team Update google sheet: https://docs.google.com/spreadsheets/d/1Lrn_g7Z92x4EPZ2OUkn3Vo1QSb5SbfqYQxAagr6zeVg/edit?pli=1#gid=0
1. Ensure the Don Efficace team is consistent with the google sheets
* Make sure constants\members.json is consistent with the above google sheet
> updates members.json for don efficace group

- constants/members.json
[Member's List](https://docs.google.com/spreadsheets/d/1F7rCv4ddH-4ucozvzU1HtGA1wtRDVrEW3IXlPKcP7Jk/edit?usp=sharing)
> S24 Members Update 

- constants/applications.ts
[Ticket Name](https://www.notion.so/uwblueprintexecs/Task-Board-db95cd7b93f245f78ee85e3a8a6a316d)
* 
1.
*
> Open Applications Fall 2024

- constants/applications.ts
[Ticket Name](https://www.notion.so/uwblueprintexecs/Task-Board-db95cd7b93f245f78ee85e3a8a6a316d)
* 
1.
*
> S24 Extend Application Date 

- constants/applications.ts
* Modified application dates for Winter 2025
> Modified application dates for W25

- components/join/Hero.tsx
* Fixed button background that was causing text to not show
> Fix background on apply button

- constants/role-specific-questions.json
- constants/short-answer-questions.json
* Update general questions
* Add role specific question for VP Talent
> Update application questions for W25

- constants/role-specific-questions.json
> Remove VP Communications Role

- constants/members.json
* Updated existing member positions
* Added new members
* Uploaded images
> Updated Member List & Images for F24

- constants/applications.ts
- constants/role-specific-questions.json
Added questions and updated dates for S25 hiring
> S25 Hiring Form Update

- components/common/Login.tsx
[Login Fails Sometime](https://www.notion.so/uwblueprintexecs/Login-Fails-Sometime-21210f3fb1dc8071acf6c00daaf53e25)
* It was failing because we were routing the user back to their previous route instead of routing them to the admin dashboard
* So, logging in from `/admin` worked, but logging in from `/admin/login` did not
1. Visit `http://localhost:3000/admin/login`
2. Log in
3. Verify that you are redirected to the admin home, instead of an empty screen or the same sign in page.
*
> [INTS25] - Fix issue where login fails sometimes
